### ISSUE TITLE
Running fortran tests locally 

### ISSUE THREAD

**Issue by jbusecke** [brodeau/aerobulk#11]
Wrong issue tracker, sorry.

**Comment by brodeau** [comment]
```
At line 64 of file src/tests/aerobulk_toy.f90 (unit = 6, file = 'stdout')
Fortran runtime error: Cannot change RECL parameter in OPEN statement
```

You're version of Gfortran is a bit old I presume, so just comment out line `OPEN(6, FORM='formatted', RECL=512)` in `src/tests/aerobulk_toy.f90`

Cheers, /laurent
