### ISSUE TITLE
Bug in mod_cdn_form_ice

### ISSUE THREAD

**Issue by virginieguemas** [brodeau/aerobulk#12]
Hi,

     In functions CdN10_f_LU12 and CdN_f_LG15, zSc is computed according to equations (31) in Lupkes et al (2012) but this equation (31) gives Sc^2 rather than Sc. Hence, in l. 108 and l. 262, zSc should be used instead of zSc*zSc. I have also reported this bug on the nemo portal.

Best regards
Virginie

**Comment by brodeau** [comment]
Ok merci Virginie, c'est fixé!
A+/laurent
