### ISSUE TITLE
compilation broken

### ISSUE THREAD

**Issue by pvthinker** [brodeau/aerobulk#2]
Hi Laurent,
First of all, thanks a lot for sharing this code.
I'm not yet able to compile the code (#03f6890). I got an error while compiling test_aerobulk.f90 (l.287 and l.294). The way TURB_COARE3P0() is called is not consistent with the way it is defined in mod_blk_coare3p0.f90.
Plus it would be valuable to have make.macro in the repository (I had to guess one).
I look forward to use your code.
Cheers,
Guillaume

**Comment by brodeau** [comment]
Salut Guillaume,

I'm heavily committing in AeroBulk these days, everything is also being included in my development version of NEMO to be merged in the trunk in December: 
https://forge.ipsl.jussieu.fr/nemo/browser/NEMO/branches/2019/dev_r11085_ASINTER-05_Brodeau_Advanced_Bulk

I'm mostly improving the cool-skin and warm layer parameterizations at he moment, pretty beta and unstable at the moment I must say!
Hence the increased f*ck-up factor...

Well, the broken compilation is fixed for now...

There is a set of make.macro templates in the "arch" directory, I personally work with "make.macro_ifort"...

If you have any constructive feedback and other comments/suggestion on AeroBulk, I'd be interested to hear about them!

Cheers, /laurent
