### ISSUE TITLE
License

### ISSUE THREAD

**Issue by koldunovn** [brodeau/aerobulk#4]
Hi @brodeau 

Thank you for making this code publicly available! I have a question about the license though. The GPL3, that you choose, is quite restrictive, and require the software that uses your code to be released under the same license as well. This is not always possible, especially for older software, that is developed under strange custom licenses. Would you consider changing to something like LGPL? This will allow others to include your code as a library, without violating the license.

**Comment by brodeau** [comment]
Hello Nikolay, 
Okay I see.... Good that you bring this up!
Which license type would you personally tend to recommend? 
/laurent

**Comment by koldunovn** [comment]
Hello Laurent, 

For my own projects, I usually use MIT license, which basically allows almost anything.

For our model (FESOM2), we use GPL2, which is a bit less restrictive than the GPL3, but already run into some problems with people who would like to use FESOM2 as part of the proprietary software. Following their request, we will probably relicense FESOM2 to LGPL, which allows using FESOM2 as a library, but at the same time receive useful changes if they implement them in the FESOM2 part. 

So, if you are not happy with MIT license, probably the LGPL is a good option.
