### ISSUE TITLE
Conda forge package?

### ISSUE THREAD

**Issue by rabernat** [brodeau/aerobulk#8]
Thanks for providing this very useful package!

We would love to help create a conda forge package for it, which would make it possible to install without compiling the Fortran code.

Would this be of interest to the project?

cc @jbusecke, @tomnicholas

**Comment by brodeau** [comment]
Hello Ryan!
Thanks for your interest in AeroBulk!
Great idea! Of course I would be interested but I must warn you I'm pretty incompetent when it comes to Conda... At least for now!
Cheers, /laurent
